### ISSUE TITLE
Hey, Why empty repo？

### ISSUE THREAD

**Issue by WildDylan** [JC-Hu/ColorExpert#1]
哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈
哈哈哈哈哈哈哈哈哈

**Comment by JC-Hu** [comment]
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑

**Comment by JC-Hu** [comment]
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
黑黑黑黑黑黑黑黑黑
